-
 name: Install Nginx and serve a static website
 hosts: prod
 become: yes
 tasks:
  - name: 
    apt:
     name: Install Nginx
     state: lates
  - name:
     name: Start Nginx
     state: started
     enabled: yes
  - name:
     name: Deploy a JS website
     copy: 
      src: index.html
      dest: /var/www/html
